[package]
name = "ps-deflate"
description = "Object wrapper around libdeflater"
version = "0.1.0-5"
edition = "2021"
license = "GPL-3.0-or-later"

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3

[dependencies]
libdeflater = "1.20.0"
thiserror = "1.0.61"
